### PR TITLE
M.rebase

### PR DESCRIPTION
**Pull request by md384**
This brings black up to newest released version https://github.com/psf/black/releases/tag/21.5b1 and adds back in our edits (2 space indent, single-quotes, expand args to one per line). I have removed the change to exclude log messages.

Please check the final 3 commits but nothing here that was already there.

See https://github.com/zumper/zumper_code/pull/28964 for the changes to zcode this will make

### CODE REVIEW

**Review by thoward27 — APPROVED** [review]
LGTM. But I think you need to update your final commit message, as it still has the logging stuff included. I'd also still prefer to see less customization, but 🤷  looks like a good rebase to me

**Comment by md384** [comment]
@thoward27 I have removed some more modifications we make so now all we do is 2 space indent and 100 column default line width. Dan is certain on wanting 2 space indentation but we can do away with the rest.

**Comment by md384** [comment]
@thoward27 what are your thoughts on switching from single to double quote? I'm tempted to leave it as single quotes since the modification here is easy and all code in our codebase uses single quotes including our JS code. As someone who works with both, it's nice to have some coherence there but given black/prettier will just fix it for you, not really a big deal. Certainly looks odd to me given I'm so used to single quote but whatever.

**Comment by thoward27** [comment]
@md384 I prefer to use as little customization as necessary, so the more we can do to get closer to standard black the better IMO. As for the single v double quote, I agree the change there is very small, if we wanted to hold onto that one for a while longer I don't think it'd be the end of the world. It's one of the most simple changes

**Comment by thoward27** [comment]
@md384 do we still need this?

**Pull request closed without merging**
